// Copies the web arcade (../games) into ./www so Capacitor can bundle it, and
// injects a config.js that tells the in-app arcade where to fetch NEW games from
// (the published web URL). Bundled games always work offline; new games listed
// in the remote manifest are pulled over the network the first time.
//
// Change the published URL here (or set CAP_REMOTE_BASE when running):
//   CAP_REMOTE_BASE="https://YOURNAME.github.io/REPO/games" npm run sync
import { cp, rm, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, '..', 'games');
const WWW = join(ROOT, 'www');

const REMOTE_BASE = process.env.CAP_REMOTE_BASE || 'https://ycymycym.github.io/docs/games';

if (!existsSync(SRC)) {
  console.error(`✗ Web source not found at ${SRC}. Run this from arcade-ios/ with ../games present.`);
  process.exit(1);
}

await rm(WWW, { recursive: true, force: true });
await mkdir(WWW, { recursive: true });
await cp(SRC, WWW, { recursive: true });

// Write runtime config the app reads before booting.
const cfg = `// Auto-generated by scripts/prepare-web.mjs — do not edit by hand.
window.ARCADE_CONFIG = ${JSON.stringify({ remoteBase: REMOTE_BASE }, null, 2)};
`;
await writeFile(join(WWW, 'config.js'), cfg);

// Inject <script src="config.js"> before the app module so it runs first.
const idxPath = join(WWW, 'index.html');
let idx = await readFile(idxPath, 'utf8');
if (!idx.includes('src="config.js"')) {
  idx = idx.replace(
    '<script type="module" src="js/app.js"></script>',
    '<script src="config.js"></script>\n  <script type="module" src="js/app.js"></script>'
  );
  await writeFile(idxPath, idx);
}

console.log(`✓ Web assets copied to www/`);
console.log(`✓ Online-update source: ${REMOTE_BASE}`);
